%% Pick approximate initial centers for all scans in one device
% This is the manual preprocessing step.
%
% Usage:
%   1. Set raw data path in local/local_paths.m.
%   2. Define scan rawName values in config/config_E7_R1C2.m.
%   3. Run this script.
%   4. Click one approximate center for each scan.
%   5. The picked centers are saved to:
%        local/initial_centers_<deviceName>.mat
%        local/initial_centers_<deviceName>.csv
%        local/initial_centers_<deviceName>_snippet.m
%
% Then run:
%   main_analyze_one_device

clear; clc; close all;

addpath(genpath(fullfile(pwd, 'functions')));
addpath(fullfile(pwd, 'config'));

cfg = config_E7_R1C2();

localDir = fullfile(cfg.paths.projectRoot, 'local');
if ~exist(localDir, 'dir'); mkdir(localDir); end
if ~exist(cfg.paths.processedData, 'dir'); mkdir(cfg.paths.processedData); end
if ~exist(cfg.paths.figures, 'dir'); mkdir(cfg.paths.figures); end

nScan = numel(cfg.scans);

scanID = nan(nScan, 1);
rawName = strings(nScan, 1);
centerX_um = nan(nScan, 1);
centerY_um = nan(nScan, 1);
sourceFile = strings(nScan, 1);
timeStamp = strings(nScan, 1);

fprintf('\n========================================\n');
fprintf('Pick initial centers for device: %s\n', cfg.deviceName);
fprintf('Number of scans: %d\n', nScan);
fprintf('Raw txt root: %s\n', cfg.paths.rawTxtRoot);
fprintf('========================================\n\n');

for ii = 1:nScan
    scanCfg = cfg.scans(ii);

    rawLabel = getfield_or(scanCfg, 'rawName', getfield_or(scanCfg, 'fileName', ''));
    fprintf('\n--- Scan %d/%d: %s ---\n', ii, nScan, rawLabel);

    data = load_pfm_data(cfg, scanCfg);

    initialGuess = [];
    if isfield(scanCfg, 'centerInitial') && ~isempty(scanCfg.centerInitial) && ...
            numel(scanCfg.centerInitial) == 2 && all(isfinite(scanCfg.centerInitial))
        initialGuess = scanCfg.centerInitial;
    end

    picked = pick_initial_center_for_scan(data, cfg, scanCfg, initialGuess);

    scanID(ii) = scanCfg.scanID;
    rawName(ii) = string(rawLabel);
    centerX_um(ii) = picked(1);
    centerY_um(ii) = picked(2);
    sourceFile(ii) = string(data.sourceFile);
    timeStamp(ii) = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));

    fprintf('Picked center for scan %d: [%.6f, %.6f] um\n', ...
        scanCfg.scanID, picked(1), picked(2));
end

centerTable = table(scanID, rawName, centerX_um, centerY_um, sourceFile, timeStamp);

matFile = fullfile(localDir, sprintf('initial_centers_%s.mat', cfg.deviceName));
csvFile = fullfile(localDir, sprintf('initial_centers_%s.csv', cfg.deviceName));
snippetFile = fullfile(localDir, sprintf('initial_centers_%s_snippet.m', cfg.deviceName));

save(matFile, 'centerTable');
writetable(centerTable, csvFile);

fid = fopen(snippetFile, 'w');
fprintf(fid, '%% Initial centers picked for %s\n', cfg.deviceName);
fprintf(fid, '%% Generated by main_pick_initial_centers.m\n\n');
for ii = 1:nScan
    fprintf(fid, 'cfg.scans(%d).centerInitial = [%.6f, %.6f];  %% %s\n', ...
        ii, centerX_um(ii), centerY_um(ii), rawName(ii));
end
fclose(fid);

fprintf('\nSaved initial centers:\n');
fprintf('  %s\n', matFile);
fprintf('  %s\n', csvFile);
fprintf('  %s\n', snippetFile);
fprintf('\nYou can now run:\n');
fprintf('  main_analyze_one_device\n\n');
